name: meu_app_testes
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  http: ^1.2.1
  mockito: ^5.4.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.8
  build_test: ^2.2.2
